version: '3'
services:

  deconz:
    container_name: deconz
    image: deconzcommunity/deconz:stable 
    restart: unless-stopped
    environment:
      - TZ=Europe/Stockholm
      - DECONZ_DEVICE=/dev/ttyACM0
    volumes:
      - ./data/deconz:/opt/deCONZ
    network_mode: host
    devices:
      - /dev/ttyACM0

  homebridge:
    container_name: homebridge
    image: oznu/homebridge:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/Stockholm
      - PGID=472
      - PUID=472
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8080
    volumes:
      - ./data/homebridge:/homebridge
    network_mode: host

## Samsung QN90 is not currently supported in HA
#  nginx-proxy:
#    container_name: nginx-proxy
#    image: nginx:stable
#    restart: unless-stopped
#    volumes:
#      - ./data/nginx-proxy/nginx.conf:/etc/nginx/nginx.conf
#    ports:
#      - '8001:8001'
#      - '8002:8002'

  ad-blocker:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/Stockholm
    volumes:
      - ./data/pi-hole/etc-pihole:/etc/pihole
      - ./data/pi-hole/etc-dnsmasq.d:/etc/dnsmasq.d
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "7070:80/tcp"
    cap_add:
      - NET_ADMIN

networks:
  default:
    name: traefik
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24
          gateway: 172.21.0.1
