services:
  traefik:
    container_name: traefik
    image: traefik:v2.4
    restart: unless-stopped
    command:
      - "--providers.docker=true"
      - "--accesslog=true"
      - "--log.format=json"
      - "--accesslog.format=json"
      - "--api"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker=true"
      - "--providers.file.filename=/dynamic.yaml"
      # Entrypoints
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      # Bind domain and resolver to websecure entrypoint
      - "--entrypoints.websecure.http.tls.certResolver=myresolver"
      - "--entrypoints.websecure.http.tls.domains[0].main=${DOMAIN}"
      - "--entrypoints.websecure.http.tls.domains[0].sans=*.${DOMAIN}"
      # Ignore self-signed backend certs
      - "--serversTransport.insecureSkipVerify=true"
      # ACME.SH settings
      - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=loopia"
      - "--certificatesresolvers.myresolver.acme.email=${LETSENCRYPT_MAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.delaybeforecheck=2"
    environment:
      - "LOOPIA_API_USER=${LOOPIA_API_USER}"
      - "LOOPIA_API_PASSWORD=${LOOPIA_API_PASSWORD}"
    volumes:
      - ./data/cert:/letsencrypt
      - ./data/traefik/dynamic.yaml:/dynamic.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
      - "443:443"
    networks:
      default:
        ipv4_address: 172.20.0.20
        aliases:
        - traefik
    # Helps routing services outside of docker i.e. containers with network_mode: host
    extra_hosts:
      - host.docker.internal:172.20.0.1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=authelia@docker"

  # Create new passwords with `docker run authelia/authelia:latest authelia hash-password 'password'`
  authelia:
    container_name: authelia
    image: authelia/authelia:4.35
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - ./data/authelia:/config
    expose:
      - 9091
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.authelia.rule=Host(`login.${DOMAIN}`)'
      - 'traefik.http.routers.authelia.entrypoints=websecure'
      - 'traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://login.${DOMAIN}/'
      - 'traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User, Remote-Groups, Remote-Name, Remote-Email'
      - 'traefik.http.middlewares.authelia-basic.forwardauth.address=http://authelia:9091/api/verify?auth=basic'
      - 'traefik.http.middlewares.authelia-basic.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia-basic.forwardauth.authResponseHeaders=Remote-User, Remote-Groups, Remote-Name, Remote-Email'

networks:
  default:
    name: traefik
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1
