# meant to be used with traefik/authelia docker-compose.yaml as base
services:
  unifi-controller:
    container_name: unifi
    image: ghcr.io/linuxserver/unifi-controller:7.5.176
    restart: unless-stopped
    environment:
      - TZ=Europe/Stockholm
      - PUID=1000
      - PGID=1000
      - MEM_LIMIT=1024
      - MEM_STARTUP=1024
    volumes:
      - ./data/unifi:/config
      - /var/log/containers/unifi:/var/log/unifi
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp 
      - 8843:8843 
      - 8880:8880
      - 6789:6789
      - 5514:5514/udp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.unifi.rule=Host(`unifi.${DOMAIN}`)"
      - "traefik.http.routers.unifi.entrypoints=websecure"
      - "traefik.http.services.unifi.loadbalancer.server.scheme=https"
      - "traefik.http.services.unifi.loadbalancer.server.port=8443"

volumes:
  uptime-kuma-storage:
  grafana-storage:
