---
  - name: reload systemd
    systemd:
       daemon-reload: yes
    become: yes
    listen: "reload docker services"
    notify: "reload docker services step 2"

  - name: restart docker
    systemd:
      name: docker
      state: restarted
    become: yes
    listen: "reload docker services step 2"
...
