---
  - name: Install pre-requisites for adding repositories
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
      update_cache: yes

  - name: Add Docker GPG key
    apt_key:
      url: "https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }}/gpg"
  
  - name: Add Docker APT repository
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
  
  - name: Install Docker CE
    apt:
      name: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-compose-plugin']
      update_cache: yes
    register: install
...
